version: '3'

volumes:
  postgres_data:
services:
  database:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  server:
    build:
      context: .
      dockerfile: dev-ops/docker/dev/server/Dockerfile
    env_file: dev-ops/env/dev.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/code
    ports:
      - "8000:8000"
    depends_on:
      - database
  client:
    build:
      context: .
      dockerfile: dev-ops/docker/dev/client/Dockerfile
    command: npm run start
    volumes:
      - /code/node_modules
      - ./client:/code
    ports:
      - "4200:4200"
    depends_on:
      - server
